name: 'MacOS-CI'
permissions:
    contents: read
    pull-requests: read

on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os:
          # x86-64
          - macos-13
          # M1 processor
          #- macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2
          submodules: false

      - name: Build it
        env:
          MY_OS_NAME: macos
          IS_RELEASE: 0
        run: script/cibuild $FLAGS
